Repository WilliamKarolDiCioccio/open_local_ui, pull requests merged in 2024-06, with the labels that each got.

#23 Remove vs code settings
  .gitignore
  .vscode/settings.json
Labels: invalid

#48 Show Flutter license page instead
  app/LICENSE
  app/lib/layout/dashboard.dart
Labels: enhancement

#57 Allow jpg file extension for images
  app/lib/dialogs/attachments_dropzone.dart
Labels: bug

#59 Better date format
  app/lib/helpers/datetime.dart
Labels: enhancement

#64 Implement automatic updater
  app/.env.dev
  app/assets/l10n/intl_de.arb
  app/assets/l10n/intl_en.arb
  app/assets/l10n/intl_es.arb
  app/assets/l10n/intl_fr.arb
  app/assets/l10n/intl_it.arb
  app/lib/dialogs/update.dart
  app/lib/env.dart
  app/lib/helpers/github.dart
  app/lib/helpers/snackbar.dart
  app/lib/helpers/update.dart
  app/lib/layout/dashboard.dart
  app/lib/main.dart
  app/lib/pages/models.dart
  app/lib/pages/sessions.dart
  app/lib/pages/settings.dart
  app/lib/pages/update_in_progress.dart
  app/lib/providers/model.dart
  app/lib/widgets/chat_example_questions.dart
  app/lib/widgets/chat_input_field.dart
  app/lib/widgets/chat_message.dart
  app/lib/widgets/chat_toolbar.dart
  app/lib/widgets/markdown_widget.dart
  app/linux/flutter/generated_plugin_registrant.cc
  app/linux/flutter/generated_plugins.cmake
  app/macos/Flutter/GeneratedPluginRegistrant.swift
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement
